version: '3.9'

services:
  db:
    image: postgres:14.3-alpine3.16
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_asyncio